<?php

/**
 * @file
 * Contains shareselecttext.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function shareselecttext_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the shareselecttext module.
    case 'help.page.shareselecttext':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is used for Selected text') . '</p>';
      return $output;

    default:
  }
}


 function shareselecttext_page_attachments(array &$attachments) {

 	
 // $attachments['#attached']['library'][] =  'shareselecttext/js/sharect.min.js';
 	//print_r($attachments['#attached']['library'][]);exit;
}


