<?php

/**
 * @file
 * Contains my_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_test module.
    case 'help.page.my_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is for Create custom table and submit data in custom table') . '</p>';
      return $output;

    default:
  }
}
